package com.jacstuff.musicplayer.view.fragments;

public enum Message {
    NOTIFY_TO_LOAD_GENRE,
    NOTIFY_TO_DESELECT_GENRE_ITEMS,
    SEND_GENRES_TO_FRAGMENT,
    SEND_ARTISTS_TO_FRAGMENT,
    SEND_TRACKS_TO_FRAGMENT,
    SCROLL_TO_CURRENT_TRACK,
    NOTIFY_TO_DESELECT_PLAYLIST_ITEMS,
    NOTIFY_TO_DESELECT_ARTIST_ITEMS,
    NOTIFY_TO_DESELECT_ALBUM_ITEMS,
    NOTIFY_TO_LOAD_ALBUM,
    NOTIFY_TO_LOAD_ARTIST,
    NOTIFY_PLAYLISTS_FRAGMENT_TO_DELETE,
    NOTIFY_PLAYLISTS_FRAGMENT_TO_CREATE,
    NOTIFY_PLAYLISTS_FRAGMENT_TO_LOAD,
    ENSURE_SELECTED_TRACK_IS_VISIBLE,
    DESELECT_CURRENT_TRACK_ITEM,
    NOTIFY_TO_REQUEST_UPDATED_PLAYLIST,
    NOTIFY_USER_PLAYLIST_LOADED

}
